#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%  %H:%M ' > "$PANEL_FIFO" &

spotify_artist() {
  if pgrep spotify > /dev/null; then
    xprop -name "Spotify Premium - Linux Preview" _NET_WM_ICON_NAME 2>/dev/null | cut -d "\"" -f 2 | cut -b 11- | awk -F " – " '{print $1}'
  fi
}

spotify_track() {
  if pgrep spotify > /dev/null; then
    xprop -name "Spotify Premium - Linux Preview" _NET_WM_ICON_NAME 2>/dev/null | cut -d "\"" -f 2 | cut -b 11- | awk -F " – " '{print $2}'
  fi
}

while true; do
	echo "D" $(mytime) > "$PANEL_FIFO" &
  echo "X" $(spotify_track) - $(spotify_artist) > "$PANEL_FIFO" &
	sleep 0.5s
done &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
