#! /bin/sh

. panel_colors

while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            ;;
        V*)
            # active openvpn connection
            if [ $(pidof openvpn) ]; then
                vpn="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_BATTERY_RED}  ${line#?}  %{B-}%{F-}"
            else
                vpn=""
            fi
            ;;
        D*)
            # battery output
            battery_life=$(acpi | head -n 1 | cut -d' ' -f4 | sed 's/.$//' | sed 's/.$//')
            status=$(acpi | head -n 1 | cut -d' ' -f3)
            battery_colour=$COLOR_TITLE_BG

            if [ $battery_life -lt 41 ]; then
                battery_colour=$COLOR_BATTERY_ORANGE
            fi

            if [ $battery_life -lt 21 ]; then
                battery_colour=$COLOR_BATTERY_RED
            fi

            if [ $status = "Charging," ]; then
                battery_colour=$COLOR_BATTERY_GREEN
            fi

            battery="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B${battery_colour}} ${line#?}  %{B-}%{F-}"
            ;;
        I*)
            # current wireless network
            wifi_network="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_TITLE_BG}%{A:wicd-gtk:} ${line#?} %{A}%{B-}%{F-}"
            ;;
        esac
        printf "%s\n" "%{l}${vpn}%{r}${sys_infos}${wifi_network}${battery}"
done
