#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
    X*)
      # spotify output
      spotify="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_TITLE_BG}%{A:bspc desktop -f IV:}${line#?}  %{A}%{B-}%{F-}"
      ;;
		S*)
			# clock output
			sys_infos="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?}  %{B-}%{F-}"
			;;
    V*)
      # active openvpn connection
      if [ $(pidof openvpn) ]; then
        vpn="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_BATTERY_RED}  VPN:${line#?}  %{B-}%{F-}"
      else
        vpn=""
      fi
      ;;
		D*)
			# battery output
      battery_life=$(acpi | head -n 1 | cut -d' ' -f4 | sed 's/.$//' | sed 's/.$//')
      status=$(acpi | head -n 1 | cut -d' ' -f3)
      battery_colour=$COLOR_TITLE_BG

      if [ $battery_life -lt 41 ]; then
        battery_colour=$COLOR_BATTERY_ORANGE
      fi

      if [ $battery_life -lt 21 ]; then
        battery_colour=$COLOR_BATTERY_RED
      fi

      if [ $status = "Charging," ]; then
        battery_colour=$COLOR_BATTERY_GREEN
      fi

			battery="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B${battery_colour}}${line#?} %{B-}%{F-}"
			;;
    I*)
      # current wireless network
      wifi_network="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_TITLE_BG}%{A:wicd-gtk:} ${line#?} %{A}%{B-}%{F-}"
      ;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# active monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_TITLE_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					m*)
						# inactive monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-}  "
						fi
						;;
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_TITLE_BG}%{U$COLOR_UNDERLINE}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_UNDERLINE}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
						;;
					L*)
						# layout
						wm_infos="$wm_infos  %{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm_infos}%{c}%{r}${vpn}${wifi_network}${spotify}${battery}${sys_infos}"
done
