#!/bin/bash

ESSID=$(iwgetid -r)
# Taken from https://github.com/windelicato/dotfiles/blob/master/.config/bspwm/panel/panel_wifi
QUAL=`iwconfig wlan0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig wlan0 | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
PERC=`echo $QUAL*100/$MAX | bc`

echo "$ESSID ($PERC%)"

