#! /bin/bash

source ~/.config/globals

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%  %a %H:%M ' > "$PANEL_FIFO" &

spotify_artist() {
  if pgrep spotify > /dev/null; then
    sp current | grep ^Artist | sed -e 's/Artist//' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
  fi
}

spotify_track() {
  if pgrep spotify > /dev/null; then
    sp current | grep ^Title | sed -e 's/Title//' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
  fi
}

while true; do
  battery_life=$(acpi -V | head -n 1 | cut -d' ' -f4)
  wifi=$(~/.config/panel/panel_wifi)
  vpn=$(ls /var/run/openvpn 2>/dev/null | grep .pid | head -n 1 | xargs -I {} basename {} .pid)
	echo "D" " ${battery_life%?}" > "$PANEL_FIFO" &
  echo "X"  $(spotify_track) - $(spotify_artist) > "$PANEL_FIFO" &
  echo "I" " ${wifi}" > "$PANEL_FIFO" &
  echo "V" "${vpn}" > "$PANEL_FIFO" &
	sleep 0.5s
done &

. panel_colors

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$PANEL_FONT_FAMILY_2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" | sh &

wait
