#!/bin/sh
export XAUTHORITY=/home/benp/.Xauthority
export DISPLAY=":0"

battery_level=`acpi -b | cut -d ' ' -f4 | grep -o '[0-9]*'

if [ $battery_level -le 10 ]; then
  notify-send "Battery low" "Battery level is at ${battery_level}%!"
fi
