#!/bin/sh
# taken from http://unix.stackexchange.com/a/84438
export XAUTHORITY=/home/benp/.Xauthority
export DISPLAY=":0"

low_threshold=10
critical_threshold=4
timeout=59
shutdown_cmd='/usr/sbin/pm-hibernate'

battery_level=$(acpi -b | cut -d ' ' -f4 | grep -o '[0-9]*' | head -n 1)
state=$(cat /sys/class/power_supply/BAT1/status)

if [ x"$state" != x'Discharging' ]; then
  exit 0
fi

do_shutdown() {
  sleep $timeout && kill $zenity_pid 2>/dev/null

  if [ x"$state" != x'Discharging' ]; then
    exit 0
  else
    $shutdown_cmd
  fi
}

if [ $battery_level -lt $low_threshold ] && [ $battery_level -gt $critical_threshold ]; then
  notify-send "Battery low" "Battery level is at ${battery_level}%!"
fi

if [ $battery_level -lt $critical_threshold ]; then
  notify-send -u critical -t 20000 "Battery level is low: $level%" \
      'The system is going to shut down in 1 minute.'

  DISPLAY=:0 zenity --question --ok-label 'OK' --cancel-label 'Cancel' \
    --text "Battery level is low: $level%.\n\n The system is going to shut down in 1 minute." &
  zenity_pid=$!

  do_shutdown &
  shutdown_pid=$!

  trap 'kill $shutdown_pid' 1

  if ! wait $zenity_pid; then
    kill $shutdown_pid 2>/dev/null
  fi
fi

exit 0
