#!/bin/bash

# source normal panel colors
source ~/.config/panel/panel_colors
source ~/.config/globals

# how long should the popup remain?
duration=3

# define geometry
barx=10
bary=10
barw=300
barh=30

(echo "   $@"; sleep ${duration}) | lemonbar -g ${barw}x${barh}+${barx}+${bary} -f "$PANEL_FONT_FAMILY" -F "#FFFFFF" -B "$COLOR_BATTERY_RED"
