#!/bin/bash

# benp 2015
#
# display some system info

source /etc/os-release
pkgcount=$(dpkg --list | wc -l)
kernel=$(uname -r)
wm=$(wmctrl -m | grep ^Name: | tr " " "\n" | tail -n 1)
font=$(cat ~/.Xresources | grep ^URxvt.font | awk -F ' ' '{print $2}' | awk -F ':' '{print $2}')
uptime=$(uptime --pretty)
shell=$(echo $SHELL)
nodeversion=$(node --version)

echo "os:        $PRETTY_NAME"
echo "kernel:    $kernel"
echo "packages:  $pkgcount"
echo "wm:        $wm"
echo "shell:     $shell"
echo "font:      $font"
echo "uptime:    $uptime"
echo "node:      $nodeversion"
