#! /bin/sh

bspc config border_width        2
bspc config window_gap          10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config remove_disabled_monitor true

bspc monitor -d I II III IV V

bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating border=off

killall panel
panel &
